# Generated by Django 2.2.7 on 2019-12-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=20)),
                ('tweet_text', models.CharField(max_length=200)),
                ('tweet_locaton', models.CharField(max_length=50)),
                ('tweet_gender', models.CharField(max_length=10)),
                ('tweet_sentiments', models.CharField(max_length=10)),
                ('retweet_count', models.CharField(max_length=15)),
            ],
        ),
    ]
