# Generated by Django 2.1.15 on 2020-09-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='twitterAPIkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consumer_key', models.CharField(max_length=100)),
                ('Consumer_secret', models.CharField(max_length=100)),
                ('Access_token', models.CharField(max_length=100)),
                ('Access_token_secret', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='tweets',
        ),
    ]
